services:
  web:
    image: my-flask-app:v2
    ports:
      - "8083:5001"
    volumes:
      - my-app-data:/app/data
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  my-app-data:
  redis-data: