pipeline {
    agent any

    stages {

        stage('Checkout Source Code') {
            steps {
                echo 'Starting Git checkout...'
                git url: 'https://github.com/riavinod10/devops-lab', branch: 'main'
                echo 'Git checkout completed.'
            }
        }

        stage('Run Example Command') {
            steps {
                echo 'Executing a shell command...'

                sh 'echo "Hello from Declarative Pipeline!"'
                sh 'echo "--- Reading README ---"'
                sh 'cat README.md'
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished.'
        }
    }
}